
development:
  adapter: postgresql
  encoding: unicode
  database: wa_development
  pool: 200
  username: Nick
  password: 

test:

  adapter: postgresql
  encoding: unicode
  database: wa_test2
  pool: 200
  username: Nick
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: wa_test2
  pool: 200
  username: Nick
  password: 