
development:
  adapter: postgresql
  encoding: unicode
  database: wa_development
  pool: 20
  username: Nick
  password: 

test:

  adapter: postgresql
  encoding: unicode
  database: wa_test
  pool: 5
  username: Nick
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: wa_test
  pool: 5
  username: Nick
  password: 