common: &common
  adapter: postgresql
  encoding: unicode
  pool: 200
  username: test
  password: 

development:
  <<: *common
  database: wa_dev

test:
  <<: *common
  database: wa_test

production:
  <<: *common
  database: wa