development:
  adapter: postgresql
  encoding: unicode
  database: wa_development
  pool: 5
  username: Nick
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: wa_test
  pool: 5
  username: Nick
  password: å